### ISSUE TITLE
Add corner information to new stops 

### ISSUE THREAD

**Issue by lauramatson** [Metropolitan-Council/ServiceAdjustmentsAPI#7]
Some of the Adj Schedule recipient systems need the corner number / corner type field for new stops created in TransitMaster. 

The information will be stored as part of the ALTERNATE_STOP table in the TMDailyLog db. The information will be visible wherever stop properties are shown and in the UI of the alternate stop dialog of stop closure and detour adjustments.

It's looking like TransitMaster will have two separate fields each with 4 options- 
1) Northbound, Southbound, Eastbound, and Westbound 
2) Nearside, Farside, Midblock, and Across From

**Comment by botanize** [comment]
The corner number makes sense, that's easy to add. The direction I don't understand. For example stop 1328 serves both NB 6 and EB 17. If it were replaced by a mid-block stop which value should it be assigned for direction?

**Comment by botanize** [comment]
I see direction + description -> corner number.

**Comment by lauramatson** [comment]
Oh, to clarify, number is a function of corner type + direction! So if number is easy, then that's it. 
![image](https://user-images.githubusercontent.com/45184776/160187343-a95a98cb-963d-4fab-824c-5846cc8c165f.png)

**Comment by botanize** [comment]
Oh, great!
